### ISSUE TITLE
show "close" button on the left side, not the right side

### ISSUE THREAD

**Issue by atsushieno** [jazz-soft/midi-player#1]
![Screenshot from 2019-03-27 16-31-21](https://user-images.githubusercontent.com/53929/55057889-d5520f80-50ad-11e9-98cb-bf9057056eb5.png)

The attached screenshot is what happens when I clicked links to `*.mid` file with jazz-midi plugin. The UI control is not very small, and it is very possible that the overlay control goes beyond the right border. Then I have to expand the window to click those close buttons. It is not user-friendly.

("Right/left" may be wrong; probably start/end is more appropriate, taking RTL direction into consideration.)

A repro website: https://en.wikipedia.org/wiki/Interval_(music)#Main_intervals

**Comment by jazz-soft** [comment]
Thank you for the hint. I'll think how to do better positioning.
But you don't actually need to expand the window, you can drag the player widget to the left instead.

**Comment by atsushieno** [comment]
Ohh, I had no idea. Thanks for the info. I'm not sure whether/how important this issue is anymore.

**Comment by jazz-soft** [comment]
I have uploaded a new version with the changes you suggested for Chrome and Firefox.
(Edge uses a longer publishing process)
Please install the new version unless your extensions are updated automatically.
Thanks again for the idea!

**Comment by atsushieno** [comment]
I tried the latest addin and it's not clipped at the end anymore. Thanks for the fix!
